-- =====================================================
-- RKISPro Dummy Customers
-- =====================================================

INSERT INTO public.customers (
    name,
    phone,
    email,
    password,
    company_name,
    location
)
VALUES
('Rajesh Sharma', '9876543210', 'rajesh@test.com', 'dummy123', 'Sharma Industries', 'Bilaspur'),
('Amit Verma', '9876543211', 'amit@test.com', 'dummy123', 'Verma Steel Works', 'Raipur'),
('Sanjay Patel', '9876543212', 'sanjay@test.com', 'dummy123', 'Patel Fabrication', 'Korba'),
('Rohit Yadav', '9876543213', 'rohit@test.com', 'dummy123', 'Yadav Engineering', 'Raigarh'),
('Deepak Tiwari', '9876543214', 'deepak@test.com', 'dummy123', 'DT Industrial', 'Bilaspur'),
('Vikas Singh', '9876543215', 'vikas@test.com', 'dummy123', 'Singh Shed Works', 'Durg'),
('Harsh Agrawal', '9876543216', 'harsh@test.com', 'dummy123', 'Agrawal Infra', 'Raipur'),
('Mohit Sahu', '9876543217', 'mohit@test.com', 'dummy123', 'Sahu Enterprises', 'Jagdalpur'),
('Nitin Jain', '9876543218', 'nitin@test.com', 'dummy123', 'Jain Manufacturing', 'Ambikapur'),
('Pankaj Gupta', '9876543219', 'pankaj@test.com', 'dummy123', 'Gupta Fabricators', 'Bilaspur');

-- =====================================================
-- RKISPro Dummy Vendors
-- =====================================================

INSERT INTO public.vendors (
    vendor_type,
    full_name,
    company_name,
    owner_name,
    phone,
    email,
    password,
    gst_number,
    location,
    services,
    machinery,
    capacity,
    worker_count,
    experience_years,
    city,
    state,
    verification_status,
    available_for_quick_booking,
    available_for_large_work,
    completed_projects_count,
    rating,
    trust_score,
    skill_categories
)
VALUES

-- Individual Vendors

(
'individual',
'Ramesh Welder',
NULL,
NULL,
'9000000001',
'ramesh@test.com',
'dummy123',
NULL,
'Bilaspur',
ARRAY['Welding','Repair'],
ARRAY['Arc Welding Machine'],
'Small',
2,
5,
'Bilaspur',
'Chhattisgarh',
'verified',
true,
false,
12,
4.5,
82,
ARRAY['Arc Welding','Gas Cutting']
),

(
'individual',
'Suresh Mechanic',
NULL,
NULL,
'9000000002',
'suresh@test.com',
'dummy123',
NULL,
'Raipur',
ARRAY['Machine Repair'],
ARRAY['Repair Tools'],
'Medium',
3,
7,
'Raipur',
'Chhattisgarh',
'verified',
true,
false,
18,
4.7,
88,
ARRAY['Industrial Maintenance']
),

(
'individual',
'Mukesh Electrician',
NULL,
NULL,
'9000000003',
'mukesh@test.com',
'dummy123',
NULL,
'Korba',
ARRAY['Electrical'],
ARRAY['Electrical Tools'],
'Small',
1,
4,
'Korba',
'Chhattisgarh',
'pending',
true,
false,
5,
4.0,
65,
ARRAY['Industrial Wiring']
),

(
'individual',
'Naresh Fabricator',
NULL,
NULL,
'9000000004',
'naresh@test.com',
'dummy123',
NULL,
'Durg',
ARRAY['Fabrication','Welding'],
ARRAY['Welding Machine'],
'Medium',
4,
6,
'Durg',
'Chhattisgarh',
'verified',
true,
true,
15,
4.6,
84,
ARRAY['Steel Fabrication']
),

(
'individual',
'Ravi Technician',
NULL,
NULL,
'9000000005',
'ravi@test.com',
'dummy123',
NULL,
'Raigarh',
ARRAY['Installation'],
ARRAY['Installation Kit'],
'Small',
2,
3,
'Raigarh',
'Chhattisgarh',
'verified',
true,
false,
8,
4.2,
70,
ARRAY['Machine Installation']
),

-- Company Vendors

(
'company',
NULL,
'Sharma Fabrication Works',
'Anil Sharma',
'9000000011',
'sharmafab@test.com',
'dummy123',
'22AAAAA0000A1Z5',
'Bilaspur',
ARRAY['Shed Fabrication','Machine Frames'],
ARRAY['CNC Machine','Hydraulic Press'],
'Large',
25,
12,
'Bilaspur',
'Chhattisgarh',
'verified',
true,
true,
48,
4.8,
94,
ARRAY[]::text[]
),

(
'company',
NULL,
'RK Steel Industries',
'Rajeev Kumar',
'9000000012',
'rksteel@test.com',
'dummy123',
'22BBBBB1111B1Z5',
'Raipur',
ARRAY['Heavy Fabrication','Industrial Structures'],
ARRAY['Laser Cutting','Welding Setup'],
'Large',
40,
15,
'Raipur',
'Chhattisgarh',
'verified',
false,
true,
72,
4.9,
97,
ARRAY[]::text[]
),

(
'company',
NULL,
'Mahadev Engineering',
'Pawan Patel',
'9000000013',
'mahadev@test.com',
'dummy123',
'22CCCCC2222C1Z5',
'Korba',
ARRAY['Mezzanine Floors','ACP Structures'],
ARRAY['Sheet Bending Machine'],
'Medium',
18,
9,
'Korba',
'Chhattisgarh',
'pending',
false,
true,
15,
4.0,
68,
ARRAY[]::text[]
),

(
'company',
NULL,
'Industrial TechFab',
'Vivek Soni',
'9000000014',
'techfab@test.com',
'dummy123',
'22DDDDD3333D1Z5',
'Raigarh',
ARRAY['Industrial Maintenance','Repair'],
ARRAY['Lathe Machine','Drilling Machine'],
'Medium',
20,
11,
'Raigarh',
'Chhattisgarh',
'verified',
true,
true,
33,
4.4,
81,
ARRAY[]::text[]
),

(
'company',
NULL,
'PowerMech Fabricators',
'Ajay Verma',
'9000000015',
'powermech@test.com',
'dummy123',
'22EEEEE4444E1Z5',
'Bilaspur',
ARRAY['Steel Structures','Shed Work'],
ARRAY['Plasma Cutter','CNC Machine'],
'Large',
35,
14,
'Bilaspur',
'Chhattisgarh',
'verified',
false,
true,
55,
4.7,
90,
ARRAY[]::text[]
);

SELECT 'RKISPro dummy customers and vendors inserted successfully.' AS message;