import type { VendorStatus, VendorType, VendorVerificationStatus } from "@/types/auth";

export type VendorRow = {
  id: string;
  company_name: string;
  owner_name: string;
  phone: string;
  email: string;
  password: string;
  gst_number: string;
  location: string;
  services: string[] | string;
  machinery: string[] | string;
  capacity: string;
  worker_count: number;
  experience_years: number;
  logo_url: string | null;
  factory_images: string[];
  status: VendorStatus;
  vendor_type: VendorType;
  full_name: string | null;
  skill_categories: string[];
  service_radius_km: number | null;
  available_for_quick_booking: boolean;
  id_proof_url: string | null;
  profile_photo_url: string | null;
  workshop_address: string | null;
  workshop_images: string[];
  available_for_large_work: boolean;
  city: string | null;
  state: string | null;
  verification_status: VendorVerificationStatus;
  verification_notes: string | null;
  pan_number?: string | null;
  agreement_accepted?: boolean;
  agreement_accepted_at?: string | null;
  rating: number;
  completed_projects_count: number;
  trust_score: number;
  created_at: string;
};

export type VendorProfile = {
  id: string;
  companyName: string;
  ownerName: string;
  phone: string;
  email: string;
  gstNumber: string;
  location: string;
  services: string;
  serviceList: string[];
  machinery: string;
  machineryList: string[];
  capacity: string;
  workerCount: number;
  experienceYears: number;
  logoUrl: string | null;
  factoryImages: string[];
  status: VendorStatus;
  vendorType: VendorType;
  fullName: string | null;
  skillCategories: string[];
  serviceRadiusKm: number | null;
  availableForQuickBooking: boolean;
  idProofUrl: string | null;
  profilePhotoUrl: string | null;
  workshopAddress: string | null;
  workshopImages: string[];
  availableForLargeWork: boolean;
  city: string | null;
  state: string | null;
  verificationStatus: VendorVerificationStatus;
  verificationNotes: string | null;
  rating: number;
  completedProjectsCount: number;
  trustScore: number;
  createdAt: string;
};
